---
name: Build
"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      matrix:
        jdk: ['21']

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false
          persist-credentials: false

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Start Test Database
        run: |
          docker compose up -d --wait --quiet-pull

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
          java-package: jdk
          cache: 'maven'

      - name: Wait for database to initialise
        run: |
          echo "Waiting for HANA to start..."
          timeout 600 bash -c "until docker logs hibernate-hdb-demo-hana-1 2>&1 | grep 'Ready at: ' > /dev/null 2>&1 ; do sleep 1 ; done"
          echo "HANA is ready..."

      - name: Build
        run: |
          mvn clean site install -B -Djdbc.url=jdbc:sap://localhost:39041 -Djdbc.user=SYSTEM -Djdbc.password=HXEHana1

      - name: Stop test resources
        if: always()
        run: |
          docker compose down > /dev/null 2>&1 || true
